// Code generated by Slice Machine. DO NOT EDIT.

import ImageText from './ImageText';
import NavigationItem from './NavigationItem';
import NewSlice from './NewSlice';
import TextSlice from './TextSlice';

export {
	ImageText,
	NavigationItem,
	NewSlice,
	TextSlice,
};

export const components = {
	image_text: ImageText,
	navigation_item: NavigationItem,
	new_slice: NewSlice,
	text_slice: TextSlice,
};
