// Code generated by Slice Machine. DO NOT EDIT.

import ImageText from './ImageText';
import NavigationItem from './NavigationItem';
import NewSlice from './NewSlice';
import TestSlice from './TestSlice';
import TextSlice from './TextSlice';

export {
	ImageText,
	NavigationItem,
	NewSlice,
	TestSlice,
	TextSlice,
};

export const components = {
	image_text: ImageText,
	navigation_item: NavigationItem,
	new_slice: NewSlice,
	test_slice: TestSlice,
	text_slice: TextSlice,
};
